### ISSUE TITLE
test failure with Python 3.11

### ISSUE THREAD

**Issue by waebbl** [alembic/alembic#411]
I'm working on adding Python 3.11 support for the Gentoo package. While the package builds, it gives an error when running the test suite and also, if installed, running python and trying to `from alembic.AbcCoreAbstract import *` (from the testsuite) or `import alembic` gives the same error `AttributeError: 'NoneType' object attribute '__doc__' is read-only ` like when running the testsuite. The excerpt from `LastTest.log` is
```
65/65 Testing: PyAlembic_Python_TEST
65/65 Test: PyAlembic_Python_TEST
Command: "/usr/bin/python3.11" "/var/tmp/portage-ondisk/portage/media-gfx/alembic-1.8.4/work/alembic-1.8.4/python/PyAlembic/Tests/RunTests.py" "PYIMATH_LOCATION-NOTFOUND/../python3.11/site-packages" "/var/tmp/portage-ondisk/portage/media-gfx/alembic-1.8.4/work/alembic-1.8.4_build/python/PyAlembic"
Directory: /var/tmp/portage-ondisk/portage/media-gfx/alembic-1.8.4/work/alembic-1.8.4_build/python/PyAlembic/Tests
"PyAlembic_Python_TEST" start time: Feb 18 11:04 CET
Output:
----------------------------------------------------------
['/var/tmp/portage-ondisk/portage/media-gfx/alembic-1.8.4/work/alembic-1.8.4/python/PyAlembic/Tests/RunTests.py', 'PYIMATH_LOCATION-NOTFOUND/../python3.11/site-packages', '/var/tmp/portage-ondisk/portage/media-gfx/alembic-1.8.4/work/alembic-1.8.4_build/python/PyAlembic']
Traceback (most recent call last):
  File "/var/tmp/portage-ondisk/portage/media-gfx/alembic-1.8.4/work/alembic-1.8.4/python/PyAlembic/Tests/RunTests.py", line 30, in <module>
    __import__(name)
  File "/var/tmp/portage-ondisk/portage/media-gfx/alembic-1.8.4/work/alembic-1.8.4/python/PyAlembic/Tests/testCacheCube2.py", line 38, in <module>
    from alembic.AbcCoreAbstract import *
AttributeError: 'NoneType' object attribute '__doc__' is read-only
<end of output>
Test time =   0.06 sec
----------------------------------------------------------
Test Failed.
"PyAlembic_Python_TEST" end time: Feb 18 11:04 CET
"PyAlembic_Python_TEST" time elapsed: 00:00:00
----------------------------------------------------------
```

The issue doesn't show when build and ran against Python 3.10.

If, in python, I first `import imath` and then `import alembic`, I get a different error `TypeError: No Python class registered for C++ class PyImath::FixedArray<bool>`. Not sure, if this is purely alembic related or if imath needs to change some exports as well for 3.11. The `dir(imath)` entry doesn't show `FixedArray` for both, Python 3.10 and 3.11, but the error only shows for Python 3.11.

**Comment by lamiller0** [comment]
Is it pulling in an imath compiled against a different version of python?

**Comment by waebbl** [comment]
No that's no the case. The dependency resolution won't resolve such a combination.
Yet, I can no longer reproduce the issue. With the currently installed Python 3.11.2 this no longer happens, and all works as expected. At the time of this report, I had Python 3.11.1 installed. Looks like this was due to some unlucky combination of packages.
I apologize for the noise.

**Comment by waebbl** [comment]
Sadly, I have to reopen the issue. While adding the 1.8.5 package, a reviewer got a very similar issue, see the PR gentoo/gentoo#30218

**Comment by lamiller0** [comment]
What combination of python, boost, and Imath?  Another user was having import issues on Windows when trying to build with boost 1.81 and python 3.8.  The package built but when alembic was imported it was lacking all of the submodules.

**Comment by waebbl** [comment]
I couldn't reproduce the issue on my test, when using boost-1.81.0, imath-3.1.6 and python-3.11. The issue only happens with Python 3.11, v3.10 tests run fine. At the time of the comment, imath-3.1.7 was not yet available, we have boost-1.80.0 and 1.81.0

**Comment by waebbl** [comment]
The failure seems to be somewhat random. Early last week the python test succeeded on a build I've executed. Yesterday, it again failed.
I wonder, if it might be related to `'RunTests.py', 'PYIMATH_LOCATION-NOTFOUND/../python3.11/site-packages'`? The PyImath location is found during configuration, but the variable `ALEMBIC_PYILMBASE_PYIMATH_LOCATION`, from which `PYIMATH_LOCATION` is computed, isn't cached and seems not be available when `python/PyAlembic/Tests/CMakeLists.txt` is executed or it fails to get the value for some other reasons. And the variable `ALEMBIC_PYILMBASE_PYIMATH_LIB` isn't actually a path, but a target specification like `Imath::PyImath_Python3_11` as you can see in the output of the cmake configuration:
```
-- Found Python 3.11.2
-- Found package Imath using: Imath::PyImath_Python3_11
-- Found Boost: /usr/lib64/cmake/Boost-1.81.0/BoostConfig.cmake (found suitable version "1.81.0", minimum requ
```

**Comment by lamiller0** [comment]
We've been running with python 3.11.4 for a while and have been successfully running the tests.
